<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ProductRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return auth()->check();
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'name' => 'required|string|max:80',
            'price' => 'required|numeric'
        ];
    }

    public function messages()
    {
        return [
            'name.required' => 'O campo nome do produto é obrigatório.',
            'name.string' => 'O campo nome do produto é do tipo texto.',
            'name.max' => 'O campo nome do produto aceita no máximo 80 carácter.',

            'price.required' => 'O campo preço é obrigatório.',
            'price.numeric' => 'O campo preço só aceita números.',

        ]; // TODO: Change the autogenerated stub
    }
}
